version: "3.9"

services:
  api:
    image: nginx
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}