version: "3.9"

services:
  api:
    build: ./api
    restart: always
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "on"
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: app.py
    ports: 
      - '5000:5000'
    volumes:
      - './api:/usr/src/app'
    networks:
      - web_network
      - db_network
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U andrea -d climate_db"]
      interval: 30s
      start_period: 1m30s
      timeout: 30s
      retries: 3

volumes:
  db_data: {}

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge